/**
 * @file src/types/logging.ts
 *
 * Canonical TypeScript types for structured financial log payloads.
 *
 * IMPORTANT — PII PROHIBITION:
 * `FinancialLogPayload` MUST NOT contain Personally Identifiable Information.
 * The following fields are explicitly prohibited:
 *   - Card numbers (full or partial unmasked)
 *   - Bank account numbers
 *   - BVN (Bank Verification Number)
 *   - Full customer names
 *
 * Use masked or tokenised references only (e.g. `userId`, `accountId`).
 */

/**
 * Represents the lifecycle status of a financial transaction at the point of logging.
 *
 * - `"pending"`  — transaction has been initiated but not yet settled
 * - `"success"`  — transaction completed successfully
 * - `"failed"`   — transaction encountered an unrecoverable error
 * - `"reversed"` — a previously completed transaction has been reversed or refunded
 */
export type FinancialEventStatus = "pending" | "success" | "failed" | "reversed";

/**
 * Represents the deployment environment in which the event was emitted.
 *
 * - `"production"`  — live customer-facing environment
 * - `"staging"`     — pre-production / QA environment
 * - `"development"` — local developer environment
 */
export type FinancialEventEnvironment = "production" | "staging" | "development";

/**
 * Structured payload for all money-movement log events.
 *
 * IMPORTANT: This type MUST NOT contain PII. Prohibited fields:
 *   - card numbers, bank account numbers, BVN, full customer names.
 * Use masked/tokenised references only.
 */
export interface FinancialLogPayload {
  /**
   * Dot-namespaced event name describing the lifecycle action.
   * Examples: `"transfer.initiated"`, `"transfer.completed"`, `"withdrawal.failed"`,
   * `"webhook.received"`, `"bill.refunded"`.
   */
  event: string;

  /**
   * Transaction amount expressed in the smallest indivisible currency unit
   * to avoid floating-point ambiguity.
   * Examples: kobo for NGN (100 kobo = ₦1), cents for USD (100 cents = $1).
   */
  amount: number;

  /**
   * ISO 4217 three-letter currency code.
   * Examples: `"NGN"`, `"USD"`, `"ACBU"`.
   */
  currency: string;

  /**
   * Opaque identifier of the user who triggered the event.
   * Must NOT be a full name, email address, or any other PII — use an internal user ID only.
   */
  userId: string;

  /**
   * Source account identifier (e.g. Stellar public key or internal account ID).
   * Must NOT be a raw bank account number — use a tokenised or masked reference.
   */
  accountId: string;

  /**
   * Client-supplied idempotency key used to deduplicate repeated requests for the same operation.
   * When no explicit key is available, the `transactionId` may be used as a fallback.
   */
  idempotencyKey: string;

  /**
   * Internal transaction reference generated by the system for each money-movement operation.
   * All lifecycle events for the same transaction must share the same `transactionId`.
   */
  transactionId: string;

  /**
   * Current status of the transaction at the time this log entry is emitted.
   * Constrained to `FinancialEventStatus` — see that type for value semantics.
   */
  status: FinancialEventStatus;

  /**
   * ISO 8601 datetime string representing when this event occurred.
   * Example: `"2024-01-15T10:30:00.000Z"`.
   * Defaults to the current UTC time if not supplied by the caller.
   */
  timestamp: string;

  /**
   * Deployment environment in which the event was emitted.
   * Constrained to `FinancialEventEnvironment`.
   * Defaults to `config.nodeEnv` if not supplied by the caller.
   */
  environment: FinancialEventEnvironment;

  /**
   * Trace or request ID used to correlate related log entries across distributed services
   * and across multiple lifecycle events for the same request or job execution.
   * Must be a non-empty string — source from `x-request-id` header or `crypto.randomUUID()`.
   */
  correlationId: string;

  // ── Optional fields ──────────────────────────────────────────────────────────

  /**
   * Target account identifier for transfer events (e.g. recipient Stellar address).
   * Must NOT be a raw bank account number.
   */
  destinationId?: string;

  /**
   * Name of the external payment provider involved in this event.
   * Examples: `"flutterwave"`, `"paystack"`.
   */
  provider?: string;

  /**
   * The payment provider's own transaction reference for this event.
   * Used to correlate internal records with provider-side audit trails.
   */
  providerRef?: string;

  /**
   * Machine-readable error code when `status` is `"failed"`.
   * Examples: `"INSUFFICIENT_FUNDS"`, `"PROVIDER_TIMEOUT"`.
   */
  errorCode?: string;

  /**
   * Human-readable description of the error when `status` is `"failed"`.
   * Must NOT contain PII (no card numbers, account numbers, or customer names).
   */
  errorMessage?: string;

  /**
   * Elapsed time in milliseconds from the initiation of the operation to this event.
   * Useful for latency monitoring and SLA tracking.
   */
  durationMs?: number;
}
